insert into instantrewterminaltransaction 
select 
TERMINALTRANSACTIONID,CARDID,TRANSACTIONDATE,SAMID,SEQUENCENUMBER,TERMINALTRANSACTIONNUMBER,
CARDTRANSACTIONNUMBER,REFERENCECODE,CARDPRODCLASSID,PROMOTIONID,RUNNINGTOTAL,OPERATORID,
COMMENTS,LOADTYPE,1 AS STATUS,PRODUCTTYPE,CREATIONDATE,0 as PERSONID,MODIFIEDDATE,DELETEDDATE,
MODIFIEDBYPERSONID,DELETEDBYPERSONID,MODIFICATIONCOMMENTS,DELETIONCOMMENTS,TRANSACTIONGROUPID,
0 as CARDVALIDATION,ACTIVITYCODEID,ACTIVITYCODE,SOURCETYPE,TRANSACTIONGENERATORID,SOURCETRANSACTIONID,
CARDLOADED,PARTOFCARDSALE,ISSUANCEFLAG,VALUE,RATECODE,RATETYPE,COMPANYEXTERNALMEMBERID,COMPANYMEMBERID,
0 as SCANCOUNT,RATENAME,SUPPLIERTRANSACTIONTYPE,MERCHANTRATEID,MERCHANTSPECIALRATEID,MERCHANTOFFERID
from instantrewsummarytransaction where status = 51 and suppliertransactiontype = 20403
and cardid != 903600399030004705

select personid from instantrewterminaltransaction 

select * from report where reportid =520862

