DROP VIEW SALECODECARDSUMMARY;

/* Formatted on 14/03/2017 11:22:38 AM (QP5 v5.287) */
CREATE OR REPLACE FORCE VIEW SALECODECARDSUMMARY
(
   CARDID,
   SALECODE,
   VOUCHERCODE,
   BOOKINGID,
   SALECODEDIRECTSALEID,
   VOUCHERSALECODECARDID,
   VOUCHERSALECODEID,
   VOUCHERID,
   TRANSACTIONTYPE,
   SALECODEOWNERID,
   SALESMERCHANTID,
   REDEMPTIONMERCHANTID,
   SALEDATE,
   REDEMPTIONDATE,
   CREATIONDATE,
   STATUS,
   CURRENCY,
   SALECOST,
   SALETAX,
   REDEMPTIONCOST,
   REDEMPTIONTAX,
   SALEINVOICERATE,
   SALEINVOICECOST,
   SALEINVOICETAX,
   REDEMPTIONINVOICERATE,
   REDEMPTIONINVOICECOST,
   REDEMPTIONINVOICETAX,
   SALEREFERENCEID,
   SALEREFERENCECODE,
   PAYMENTREFERENCE,
   PAYMENTTYPE,
   SALEINVOICESTATUS,
   SALEINVOICEID,
   RETAILCUSTOMERID,
   SALECODENAME,
   PERSONNAME,
   SALESMERCHANTNAME,
   REDEMPTIONMERCHANTNAME,
   ISSUEDDATE,
   DISTRIBUTORID,
   PMSALECOST,
   PMSALETAX,
   PMCURRENCY,
   PMSALEINVOICERATE,
   PMSALEINVOICECOST,
   PMSALEINVOICETAX,
   SALEINVOICEDATE,
   PMSALEINVOICEDATE,
   CREDITNOTEFLAG,
   CREDITNOTEID,
   PMCREDITNOTEFLAG,
   PMCREDITNOTEID
)
AS
   SELECT d.cardid AS cardid,
          d.salecode AS salecode,
          NULL AS vouchercode,
          0 AS bookingid,
          d.salecodedirectsaleid AS salecodedirectsaleid,
          0 AS vouchersalecodecardid,
          0 AS vouchersalecodeid,
          0 AS voucherid,
          10 AS transactiontype,
          d.salecodeownerid,
          d.salesmerchantid AS salesmerchantid,
          0 AS redemptionmerchantid,
          d.saledate AS saledate,
          d.saledate AS redemptiondate,
          d.creationdate AS creationdate,
          d.status AS status,
          d.currency AS currency,
          d.salecost AS salecost,
          d.saletax AS saletax,
          0 AS redemptioncost,
          0 AS redemptiontax,
          d.saleinvoicerate AS saleinvoicerate,
          d.saleinvoicecost AS saleinvoicecost,
          d.saleinvoicetax AS saleinvoicetax,
          0 AS redemptioninvoicerate,
          0 AS redemptioninvoicecost,
          0 AS redemptioninvoicetax,
          d.salereferenceid AS salereferenceid,
          d.salereferencecode AS salereferencecode,
          d.paymentreference AS paymentreference,
          0 AS PAYMENTTYPE,
          d.saleinvoicestatus AS saleinvoicestatus,
          d.saleinvoiceid AS saleinvoiceid,
          d.retailcustomerid AS retailcustomerid,
          retrievesalecodename (d.salecode) AS salecodename,
          retrieveretailname (d.retailcustomerid) AS personname,
          retrievedisplayname (d.salesmerchantid) AS salesmerchantname,
          '' AS redemptionmerchantname,
          d.saledate AS issueddate,
          d.DISTRIBUTORID,
          d.PMSALECOST,
          d.PMSALETAX,
          d.PMCURRENCY,
          d.PMSALEINVOICERATE,
          d.PMSALEINVOICECOST,
          d.PMSALEINVOICETAX,
          d.SALEINVOICEDATE,
          d.PMSALEINVOICEDATE,
          d.CREDITNOTEFLAG,
          d.CREDITNOTEID,
          d.PMCREDITNOTEFLAG,
          d.PMCREDITNOTEID
     FROM salecodedirectsale d
    WHERE d.status < 50
   UNION ALL
   SELECT c.cardid AS cardid,
          c.salecode AS salecode,
          v.vouchercode AS vouchercode,
          c.bookingid AS bookingid,
          0 AS salecodedirectsaleid,
          c.vouchersalecodecardid AS vouchersalecodecardid,
          c.vouchersalecodeid AS vouchersalecodeid,
          c.voucherid AS voucherid,
          11 AS transactiontype,
          s.salecodeownerid,
          s.salesmerchantid AS salesmerchantid,
          s.redemptionmerchantid AS redemptionmerchantid,
          s.saledate AS saledate,
          s.redemptiondate AS redemptiondate,
          s.creationdate AS creationdate,
          c.status AS status,
          c.currency AS currency,
          c.salecost AS salecost,
          c.saletax AS saletax,
          0 AS redemptioncost,
          0 AS redemptiontax,
          c.saleinvoicerate AS saleinvoicerate,
          c.saleinvoicecost AS saleinvoicecost,
          c.saleinvoicetax AS saleinvoicetax,
          0 AS redemptioninvoicerate,
          0 AS redemptioninvoicecost,
          0 AS redemptioninvoicetax,
          0 AS salereferenceid,
          '' AS salereferencecode,
          v.paymentreference AS paymentreference,
          v.paymenttype AS PAYMENTTYPE,
          s.saleinvoicestatus AS saleinvoicestatus,
          s.saleinvoiceid AS saleinvoiceid,
          v.retailcustomerid AS retailcustomerid,
          retrievesalecodename (s.salecode) AS salecodename,
          retrieveretailname (v.retailcustomerid) AS personname,
          retrievedisplayname (s.salesmerchantid) AS salesmerchantname,
          retrievedisplayname (s.redemptionmerchantid)
             AS redemptionmerchantname,
          v.datetoinvoice AS issueddate,
          s.DISTRIBUTORID,
          c.PMSALECOST,
          c.PMSALETAX,
          c.PMCURRENCY,
          c.PMSALEINVOICERATE,
          c.PMSALEINVOICECOST,
          c.PMSALEINVOICETAX,
          s.SALEINVOICEDATE,
          s.PMSALEINVOICEDATE,
          c.CREDITNOTEFLAG,
          c.CREDITNOTEID,
          c.PMCREDITNOTEFLAG,
          c.PMCREDITNOTEID
     FROM vouchersalecodecard c, vouchersalecode s, voucher v
    WHERE     c.vouchersalecodeid = s.vouchersalecodeid
          AND c.voucherid = v.voucherid
          AND v.status < 50
          AND v.datetoinvoice IS NOT NULL;
