ALTER TABLE SUPPLIERINVOICE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SUPPLIERINVOICE CASCADE CONSTRAINTS;

CREATE TABLE SUPPLIERINVOICE
(
  SUPPLIERINVOICEID              INTEGER,
  PRODUCTMGRID                   INTEGER,
  OPERATORID                     INTEGER,
  EXTERNALID                     VARCHAR2(250 BYTE),
  OPERATORNAME                   VARCHAR2(250 BYTE),
  CODE                           VARCHAR2(250 BYTE),
  STATUS                         INTEGER,
  REPORTID                       INTEGER,
  PARENTREPORTID                 INTEGER,
  RELATIONSHIPTYPE               INTEGER,
  GROUPREPORTID                  INTEGER,
  INVOICEID                      VARCHAR2(250 BYTE),
  STARTDATE                      DATE,
  ENDDATE                        DATE,
  INVOICEDATE                    DATE,
  GENERATEDDATE                  DATE,
  INVOICENUMBER                  VARCHAR2(250 BYTE),
  CURRENCY                       VARCHAR2(250 BYTE),
  ROLLEDOVER                     INTEGER,
  TAXINVOICENUMBER               VARCHAR2(100 BYTE),
  AMOUNTDUEBYPM                  NUMBER(38,6)   DEFAULT 0,
  TAXAMOUNTDUEBYPM               NUMBER(38,6)   DEFAULT 0,
  AMOUNTDUETOPM                  NUMBER(38,6)   DEFAULT 0,
  TAXAMOUNTDUETOPM               NUMBER(38,6)   DEFAULT 0,
  INVOICEAMOUNTDUEBYPM           NUMBER(38,6)   DEFAULT 0,
  INVOICETAXAMOUNTDUEBYPM        NUMBER(38,6)   DEFAULT 0,
  PRETAXPAYABLEBYPMADJUSTMENTS   NUMBER(38,6)   DEFAULT 0,
  PRETAXPAYABLEBYPMCHARGES       NUMBER(38,6)   DEFAULT 0,
  PRETAXPAYABLEBYPMTRANSACTIONS  NUMBER(38,6)   DEFAULT 0,
  PRETAXPAYABLETOPMADJUSTMENTS   NUMBER(38,6)   DEFAULT 0,
  PRETAXPAYABLETOPMCHARGES       NUMBER(38,6)   DEFAULT 0,
  PRETAXPAYABLETOPMTRANSACTIONS  NUMBER(38,6)   DEFAULT 0,
  TAXPAYABLEBYPMADJUSTMENTS      NUMBER(38,6)   DEFAULT 0,
  TAXPAYABLEBYPMCHARGES          NUMBER(38,6)   DEFAULT 0,
  TAXPAYABLEBYPMTRANSACTIONS     NUMBER(38,6)   DEFAULT 0,
  TAXPAYABLETOPMADJUSTMENTS      NUMBER(38,6)   DEFAULT 0,
  TAXPAYABLETOPMCHARGES          NUMBER(38,6)   DEFAULT 0,
  TAXPAYABLETOPMTRANSACTIONS     NUMBER(38,6)   DEFAULT 0
)
TABLESPACE SORSE_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PKSUPPLIERINVOICE ON SUPPLIERINVOICE
(SUPPLIERINVOICEID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SUPPLIERINVOICENDX1 ON SUPPLIERINVOICE
(REPORTID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SUPPLIERINVOICENDX2 ON SUPPLIERINVOICE
(PRODUCTMGRID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX SUPPLIERINVOICENDX3 ON SUPPLIERINVOICE
(OPERATORID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SUPPLIERINVOICE ADD (
  CONSTRAINT PKSUPPLIERINVOICE
  PRIMARY KEY
  (SUPPLIERINVOICEID)
  USING INDEX PKSUPPLIERINVOICE
  ENABLE VALIDATE);


--------------------------------------------------------------------------------

ALTER TABLE CHARGESUPPLIERINVOICE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHARGESUPPLIERINVOICE CASCADE CONSTRAINTS;

CREATE TABLE CHARGESUPPLIERINVOICE
(
  CHARGESUPPLIERINVOICEID       INTEGER,
  SUPPLIERINVOICEID             INTEGER,
  PRODUCTMGRID                  INTEGER,
  REPORTID                      INTEGER,
  ACCOUNTNUMBER                 INTEGER,
  STATUS                        INTEGER,
  AMOUNTDUE                     NUMBER(38,6)    DEFAULT 0,
  CARDPRODCLASSID               INTEGER,
  CARDTYPE                      INTEGER,
  CHARGECATEGORYCLASSIFICATION  VARCHAR2(250 BYTE),
  CHARGECATEGORYTYPE            INTEGER,
  FREQUENCY                     VARCHAR2(250 BYTE),
  NETRATE                       NUMBER(38,6)    DEFAULT 0,
  OPERATORID                    INTEGER,
  PRODUCTTYPE                   INTEGER,
  QUANTITY                      INTEGER,
  SUBTOTAL                      NUMBER(38,6)    DEFAULT 0,
  TAX                           NUMBER(38,6)    DEFAULT 0,
  TAXINVOICEDATE                DATE,
  TAXINVOICENUMBER              VARCHAR2(100 BYTE),
  PRODUCTNAME                   VARCHAR2(250 BYTE),
  SOURCETYPE                    INTEGER,
  MERCHANTOFFERID               INTEGER
)
TABLESPACE SORSE_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX CHARGESUPPLIERINVOICENDX1 ON CHARGESUPPLIERINVOICE
(REPORTID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX CHARGESUPPLIERINVOICENDX2 ON CHARGESUPPLIERINVOICE
(PRODUCTMGRID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX CHARGESUPPLIERINVOICENDX3 ON CHARGESUPPLIERINVOICE
(OPERATORID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PKCHARGESUPPLIERINVOICE ON CHARGESUPPLIERINVOICE
(CHARGESUPPLIERINVOICEID)
NOLOGGING
TABLESPACE SORSE_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CHARGESUPPLIERINVOICE ADD (
  CONSTRAINT PKCHARGESUPPLIERINVOICE
  PRIMARY KEY
  (CHARGESUPPLIERINVOICEID)
  USING INDEX PKCHARGESUPPLIERINVOICE
  ENABLE VALIDATE);

DROP SEQUENCE SUPPLIERINVOICEID;

CREATE SEQUENCE SUPPLIERINVOICEID
  START WITH 10
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE CHARGESUPPLIERINVOICEID;

CREATE SEQUENCE CHARGESUPPLIERINVOICEID
  START WITH 10
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
