SET DEFINE OFF;
Insert into CUSTOMERINFORMATION
   (PERSONID, PERSONTYPE, PRODUCTMGRID, EXTERNALID, TITLE, 
    GIVENNAME, FAMILYNAME, ADDRESSLINE1, CITYSUBURB, STATE, 
    POSTCODE, COUNTRY, MOBILEPHONE, EMAILADDRESS, CREATIONDATE, 
    STATUS, UPPERGIVENNAME, UPPERFAMILYNAME, UPPEREMAILADDRESS, CUSTOMERSECURITYPRINCIPALID, 
    CARDNAME, PIN)
 Values
   (3563692, 1, 22181, 'R2735107', 'Ms', 
    'Lara', 'Wallace', 'Level 13, 201 Elizabeth St', 'Sydney', 'NSW', 
    '2000', 'AU', '0428088201', 'lara.wallace@harpercollins.com.au', TO_DATE('18/06/2018 3:02:54 PM', 'DD/MM/YYYY HH:MI:SS AM'), 
    0, 'LARA', 'WALLACE', 'LARA.WALLACE@HARPERCOLLINS.COM.AU', 312793, 
    'LARA WALLACE', 0);
COMMIT;
